### ISSUE TITLE
Provide a way to run Twig snippets with the C extension enabled

### ISSUE THREAD

**Issue by stof** [ninsuo/twigfiddle#10]
This could be achieved by running processes like ``php -d path/to/twig.so ...``.

There are cases where a bug can be related to the usage of the C extension, and reproducing it needs to use it.

**Comment by ninsuo** [comment]
Yeah, as soon as twig contributors make 2 times the job, we want to test if our changes are working well.
Good idea.

**Comment by ninsuo** [comment]
I implemented this and it works well on a mac environment...
But in production (Ubuntu), changing extension_dir using -d makes all other extensions unavailable.
I'm going to revert until I find something.

**Comment by stof** [comment]
you should not change the whole extension_dir IMO, as you would have to copy all extensions to this new folder too.

Use ``-d extension=/absolute/path/to/twig.so`` instead

**Comment by ninsuo** [comment]
Yeah, was thinking about linking my existing extensions to all `modules/` created in ext/twig.
Of course your solution is cleaner, will try tonight. 
Thanks!

**Comment by ninsuo** [comment]
This is working now.
Enjoy :)
