### ISSUE TITLE
Add an option to turn on strict variables

### ISSUE THREAD

**Issue by stof** [ninsuo/twigfiddle#21]
It is often useful to run templates with strict variables turned on to handle the case of mistakes in variables. I don't see any way to control this currently.

**Comment by ninsuo** [comment]
Enjoy!
https://twigfiddle.com/lbyxn1

**Comment by ninsuo** [comment]
![screen shot 2016-12-21 at 21 40 47](https://cloud.githubusercontent.com/assets/4152132/21405417/2d6effc0-c7c6-11e6-9283-46615a81a20e.png)

**Comment by stof** [comment]
great
