### ISSUE TITLE
V1Engine passes a wrong second argument to Twig_Loader_Filesystem in recent versions

### ISSUE THREAD

**Issue by stof** [ninsuo/twigfiddle#26]
The V1Engine passes the cache directory to the second argument of Twig_Loader_Filesystem for compat with very old versions of Twig 1.x

But recent versions of Twig 1.x use this argument in another way, which might cause issues.

**Comment by stof** [comment]
Here is my proposal:

- drop support for Twig versions passing the cache folder to the loader (do you really need to keep support for Twig 0.9.2 and older ? Is there anyone really using it recently ?)
- go back to a single engine then (as the only difference would be the usage of the deprecated Twig_Autoloader then, and you can use your own autoloader even in Twig 1.x, removing the need to ignore the deprecation)

what do you think ?

**Comment by ninsuo** [comment]
From data, I see that the oldest version used so far is Twig 1.1.0.
And as soon as twigfiddle claims to support 1.x and 2.x, I've nothing against removing support to 0.x.

**Comment by ninsuo** [comment]
Now, Twig 2.x and 1.x use V2 engine, where Twig 0.x uses engine V1. 
In Twig-0.9.10 (last version supported), Loader doesn't take a 2nd argument, so there will be no issues.
