### ISSUE TITLE
Showing the compiled templates should be available in case of runtime errors

### ISSUE THREAD

**Issue by stof** [ninsuo/twigfiddle#27]
Currently, when there is an error, the display of the compiled templates is not available.

While this makes sense for syntax errors (there is no compiled template yet), it would be great to have it in other cases (for runtime errors for instance)

**Comment by ninsuo** [comment]
Good catch 👍 
There may even be a compiled template if an included/imported template throws a syntax error.
There are no reason to stop the process because of an execution error.
