### ISSUE TITLE
Incomplete SSL certificate chain

### ISSUE THREAD

**Issue by z38** [ninsuo/twigfiddle#33]
At the moment, twigfiddle.com seems to send an incomplete SSL certificate chain. This causes Firefox to show a certificate error.

SSL Labs report: https://www.ssllabs.com/ssltest/analyze.html?d=twigfiddle.com
Gandi intermediate certificates: https://wiki.gandi.net/en/ssl/intermediate

**Comment by ninsuo** [comment]
Thank you for the information! :+1:

**Comment by ninsuo** [comment]
This is now fixed, thanks again for your kind warning.
