### ISSUE TITLE
Fatal errors without debug mode

### ISSUE THREAD

**Issue by ninsuo** [ninsuo/twigfiddle#34]
The following fiddle: https://twigfiddle.com/3pcjby

Makes cli crash without placing himself into the debug directory.

**Comment by stof** [comment]
Well, this is due to an infinite loop (`main.twig` template extending itself). Twig does not protect against this (which would be hard to do without performance impact).

**Comment by ninsuo** [comment]
Yep and I actually don't mind about infinite recursions, i should have opened this a bit tired :)
Thanks
