### ISSUE TITLE
[suggestion] enable strict variables by default for new fiddles

### ISSUE THREAD

**Issue by stof** [ninsuo/twigfiddle#35]
The option to enable strict variables is quite hidden in the UI.

twigfiddle is often used to report reproducing test cases for Twig (it is even the official recommendation). But enabling strict variables often allows to discover the issue (as Twig fails loudly rather than returning `null` for access to undefined methods or variables).

What do you think about enabling it by default for new fiddles (this is to ensure we don't change the behavior of existing fiddles), while keeping the option to disable it (in case you want to reproduce a bug happening only without strict mode) ?

**Comment by ninsuo** [comment]
👍

**Comment by ninsuo** [comment]
done -
this option is persisted so existing fiddles won't be affected
