### ISSUE TITLE
twigfiddle.com works in PHP7, but Twig C extension doesn't support it.

### ISSUE THREAD

**Issue by ninsuo** [ninsuo/twigfiddle#37]
All use of the C extension end up with a fatal error:

```
PHP Startup: Unable to load dynamic library 'twigfiddle:web/app/../../cli/twig/uncompressed/Twig-1.29.0/ext/twig/modules/twig.so' - twigfiddle:web/app/../../cli/twig/uncompressed/Twig-1.29.0/ext/twig/modules/twig.so: undefined symbol: zval_used_for_init
```

Sample: https://twigfiddle.com/1kmsil

**Comment by stof** [comment]
The C extension is for 5.x only (perf improvements of PHP 7 itself made it unnecessary to maintain a C extension for part of Twig, as the rewritten extension has not shown any perf improvments, especially given other optimizations performed in the userland implementation)

**Comment by stof** [comment]
Maybe the option to use the C extension should be dropped entirely, given that Twig 2 does not have this extension (see #42) and that you run code on PHP 7 which does not have the extension.

**Comment by ninsuo** [comment]
Hi there,
C extensions removed in #56 
Cheers
