### ISSUE TITLE
Template limited to 8192 characters

### ISSUE THREAD

**Issue by aukevann** [ninsuo/twigfiddle#43]
Hi, 

We can't run scripts longer than 8192 characters. Can that be changed, really inconvenient for our development.

Thanks much in advance,
Auke

**Comment by ninsuo** [comment]
Hi,

How much would you like to use?

A

**Comment by aukevann** [comment]
Hi Alain,

Thanks for your response.
128 KB would work for us.

Kind regards,

Auke van Nimwegen
[cid:image001.png@01D2E5FB.51FE2D90]
The Netherlands
M + 31 6 47910979
Skype aukevann

Volg ons / Follow us:
[/Users/auke/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1309561107]<https://www.facebook.com/valuematch>  [/Users/auke/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1316597352] <https://twitter.com/ValueMatchNL>   [/Users/auke/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1144744660] <https://www.linkedin.com/company/valuematch/>


Van: Alain Tiemblo <notifications@github.com>
Beantwoorden - Aan: ninsuo/twigfiddle <reply@reply.github.com>
Datum: dinsdag 13 februari 2018 om 11:46
Aan: ninsuo/twigfiddle <twigfiddle@noreply.github.com>
CC: Auke van Nimwegen <auke@artofleadership.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [ninsuo/twigfiddle] Template limited to 8192 characters (#43)


Hi,

How much would you like to use?

A

**Comment by ninsuo** [comment]
You really have 128kb templates? 
Kinda huge, I don't know how will behave twigfiddle but output should be not easy to read.

**Comment by aukevann** [comment]
We use it to create PDF documents. TwigFiddle we use to check the syntax, the output is less important. We have a lot of text in the template, that is why it is big. It would really help our development if you can change this, thanks.

Kind regards,

Auke van Nimwegen
[cid:image001.png@01D2E5FB.51FE2D90]
The Netherlands
M + 31 6 47910979
Skype aukevann

Volg ons / Follow us:
[/Users/auke/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1797289645]<https://www.facebook.com/valuematch>  [/Users/auke/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_494376261] <https://twitter.com/ValueMatchNL>   [/Users/auke/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1230533428] <https://www.linkedin.com/company/valuematch/>


Van: Alain Tiemblo <notifications@github.com>
Beantwoorden - Aan: ninsuo/twigfiddle <reply@reply.github.com>
Datum: dinsdag 13 februari 2018 om 12:55
Aan: ninsuo/twigfiddle <twigfiddle@noreply.github.com>
CC: Auke van Nimwegen <auke@artofleadership.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [ninsuo/twigfiddle] Template limited to 8192 characters (#43)


You really have 128kb templates?
Kinda huge, I don't know how will behave twigfiddle but output should be not easy to read.

**Comment by aukevann** [comment]
Great, many thanks Alain.

Cheers,

Auke van Nimwegen
[cid:image001.png@01D2E5FB.51FE2D90]
The Netherlands
M + 31 6 47910979
Skype aukevann

Volg ons / Follow us:
[/Users/auke/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1746451483]<https://www.facebook.com/valuematch>  [/Users/auke/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_2124157314] <https://twitter.com/ValueMatchNL>   [/Users/auke/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1653799477] <https://www.linkedin.com/company/valuematch/>


Van: Alain Tiemblo <notifications@github.com>
Beantwoorden - Aan: ninsuo/twigfiddle <reply@reply.github.com>
Datum: dinsdag 13 februari 2018 om 13:20
Aan: ninsuo/twigfiddle <twigfiddle@noreply.github.com>
CC: Auke van Nimwegen <auke@artofleadership.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [ninsuo/twigfiddle] Template limited to 8192 characters (#43)


All right, I updated the codebase and released the change.
I may remove it if I notice abuses on it, but for now that's ok 👍 .
Enjoy,
Alain
