### ISSUE TITLE
A Twig's runtime exception has been trown.

### ISSUE THREAD

**Issue by ben-rogerson** [ninsuo/twigfiddle#45]
A spelling error on the word 'trown' - should be 'thrown'.

**Comment by ninsuo** [comment]
And it's not a Twig's error runtime but a Twig error runtime .. 👍 
Thanks I will fix! 
Alain

**Comment by ninsuo** [comment]
Done! https://twigfiddle.com/fyrh19
Cheers

**Comment by ben-rogerson** [comment]
Nice one!
