### ISSUE TITLE
Null coalescing operator

### ISSUE THREAD

**Issue by ben-rogerson** [ninsuo/twigfiddle#47]
Looks like an issue using the null coalescing operator.

This should work:

```twig
{{ variable ?? "Fallback" }}
```

But I receive an error instead:
`The "defined" test only works with simple variables.`

**Comment by ninsuo** [comment]
Hi,

Can you please send a fiddle reproducing the issue?

Seems working with Twig 2.5.0: https://twigfiddle.com/98sbao

Cheers

**Comment by ben-rogerson** [comment]
Sorry, I wasn't able to replicate the issue a second time.
