### ISSUE TITLE
Raw output is misleading with leading newlines

### ISSUE THREAD

**Issue by stof** [ninsuo/twigfiddle#54]
See https://twigfiddle.com/oxixzf and https://twigfiddle.com/0nw355

Both of them are rendering an output with a leading newline. But the raw output panel strips this newline.
The panel showing the compiled template provides a proof that the newline is part of the Twig rendering.

This triggered a false bug report on Twig (the first fiddle is part of https://github.com/twigphp/Twig/issues/3162, the second is my attempt at proving it is a twigfiddle issue instead).

**Comment by ninsuo** [comment]
Hey Stof,

Thanks for the report, will fix it soon enough.

Cheers,
Alain
