### ISSUE TITLE
Template outputting only "0" don't render anything

### ISSUE THREAD

**Issue by ericmorand** [ninsuo/twigfiddle#60]
Consider the following template:

```twig
0
```

Rendering that template outputs nothing:

https://twigfiddle.com/ayv6cz

It should output `0`.

TwigPHP executed from the command line outputs `0`, as expected.

**Comment by ninsuo** [comment]
Hello @ericmorand ,

Thank you for the report, issue is now fixed.

Have a good day,
Alain
