### ISSUE TITLE
Uncaught Error: Class 'Twig_SimpleFilter' not found in twigfiddle:cli/src/Fuz/Process/Loader/Psr4Loader.php:56

### ISSUE THREAD

**Issue by ilya-zarezenko** [ninsuo/twigfiddle#75]
![image](https://user-images.githubusercontent.com/52481334/153696401-d4f0b801-2a81-40e4-b064-bf3b91a24eed.png)

**Comment by ninsuo** [comment]
Thanks, fixed.
